---
version: '2'
services:
  zookeeper-source:
    image: confluentinc/cp-zookeeper:5.5.1
    hostname: zookeeper-source
    container_name: zookeeper-source
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-source:
    image: confluentinc/cp-kafka:5.5.1
    hostname: kafka-source
    container_name: kafka-source
    depends_on:
      - zookeeper-source
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-source:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-source:29092,PLAINTEXT_HOST://kafka-source:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      
  topic-creation:
    image: confluentinc/cp-kafka:5.5.1
    hostname: topic-creation
    container_name: topic-creation
    command: bash -c "cub kafka-ready -z zookeeper-source:2181 1 90 && kafka-topics --zookeeper zookeeper-source:2181 --create --topic message_topic3 --partitions 1 --replication-factor 1 && kafka-topics --zookeeper zookeeper-source:2181 --create --topic message_count  --partitions 1 --replication-factor 1"
    depends_on:
      - zookeeper-source
      
  zookeeper-destination:
    image: confluentinc/cp-zookeeper:5.5.1
    hostname: zookeeper-destination
    container_name: zookeeper-destination
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      
  kafka-destination:
    image: confluentinc/cp-kafka:5.5.1
    hostname: kafka-destination
    container_name: kafka-destination
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-destination:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-destination:29092,PLAINTEXT_HOST://kafka-destination:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - zookeeper-destination
      
  hubapi:
    image: hubapi
    hostname: hubapi
    container_name: hubapi
    environment:
       KAFKA_BOOT_STRAP_SERVER: 'kafka-source:29092'
    depends_on:
       - kafka-source
    ports:
      - 9001:9001
      
  streamjob:
    image: streamjob
    hostname: streamjob
    container_name: streamjob
    command: bash -c "cub kafka-ready -z zookeeper-source:2181 1 120 && cub kafka-ready -z zookeeper-destination:2181 1 120"
    depends_on:
       - kafka-source
       
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    restart: unless-stopped
    hostname: elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=test
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - "./esdata:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.2
    hostname: kibana
    container_name: kibana
    volumes:
      - "./configs/kibana.yml:/usr/share/kibana/config/kibana.yml"
    restart: unless-stopped
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:7.8.0
    hostname: logstash
    container_name: logstash
    volumes:
      - "./configs/logstash.conf:/config-dir/logstash.conf"
    restart: unless-stopped
    command: logstash -f /config-dir/logstash.conf
    ports:
      - "9600:9600"
      - "7777:7777"
    links:
      - elasticsearch
      - kafka-source
      
  mirror-maker:
    image: confluentinc/cp-kafka:5.5.1
    hostname: mirror-maker
    container_name: mirror-maker
    volumes:
      - ./configs/consumer.cfg:/etc/consumer.cfg
      - ./configs/producer.cfg:/etc/producer.cfg
    command: bash -c "cub kafka-ready -z zookeeper-source:2181 1 90 && cub kafka-ready -z zookeeper-destination:2181 1 90 && kafka-mirror-maker --consumer.config /etc/consumer.cfg --producer.config /etc/producer.cfg --whitelist message_topic3  --num.streams 1"
    depends_on:
      - kafka-source
      - kafka-destination
      - zookeeper-destination
      - zookeeper-source      
      
volumes:
  esdata: